name: datascience_proyecto
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas=2.3.2
  - matplotlib=3.10.6
  - numpy=2.0.1
  - jupyter=1.1.1
  - jupyterlab=4.4.7
  - ipykernel=6.30.1
  - notebook=7.4.5
  - pip
  - pip:
    - python-dotenv  # Para cargar variables del archivo .env